#!/usr/bin/env python3
"""
Example usage of TTrainer for ablation experiments

This script demonstrates how to use TTrainer compared to TryTrainer
for ablation studies on datasets with extreme class imbalance.
"""

# NOTE: This is a usage example. To actually run this, you need:
# 1. A properly configured nnUNet environment
# 2. A dataset prepared according to nnUNet specifications
# 3. Plans and configuration files generated by nnUNet

# Example 1: Basic usage with TTrainer
def example_basic_ttrainer():
    """
    Basic example of using TTrainer
    """
    from LogWeightednnUNetTrainer import TTrainer
    import torch
    
    # Prepare your dataset according to nnUNet format
    # This is a placeholder - replace with your actual data
    plans = {
        # Your nnUNet plans
    }
    
    configuration = "3d_fullres"  # or "2d", "3d_lowres", etc.
    fold = 0  # Cross-validation fold
    
    dataset_json = {
        "labels": {
            "0": "background",
            "1": "class1",
            # ... your class labels
        }
    }
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # Initialize TTrainer
    trainer = TTrainer(
        plans=plans,
        configuration=configuration,
        fold=fold,
        dataset_json=dataset_json,
        device=device
    )
    
    # The trainer will automatically:
    # 1. Inherit all TryTrainer configurations (hybrid attention, loss function)
    # 2. Add hierarchical Mamba modules to encoder, bottleneck, and decoder
    # 3. Configure all modules on initialization
    
    # Start training
    # trainer.run_training()
    
    print("TTrainer initialized successfully!")
    print(f"  - Encoder Mamba modules: {len(trainer.encoder_mamba_modules)}")
    print(f"  - Bottleneck Mamba: {'✅' if trainer.bottleneck_mamba else '❌'}")
    print(f"  - Decoder SG-Mamba modules: {len(trainer.decoder_sg_mamba_modules)}")


# Example 2: Comparison with TryTrainer for ablation study
def example_ablation_study():
    """
    Example of running ablation study comparing TryTrainer and TTrainer
    """
    print("="*80)
    print("Ablation Study: TryTrainer vs TTrainer")
    print("="*80)
    
    print("\nExperiment Setup:")
    print("  Baseline: TryTrainer")
    print("    - Hybrid attention (class-balanced + multi-scale)")
    print("    - Dice+CE loss (Dice excludes background)")
    print("    - Standard nnUNet architecture")
    
    print("\n  Experimental: TTrainer")
    print("    - Same hybrid attention")
    print("    - Same Dice+CE loss")
    print("    - + Local Mamba (shallow encoder)")
    print("    - + Hierarchical Mamba (middle encoder)")
    print("    - + Conditional Selective Mamba (bottleneck)")
    print("    - + Semantic-Guided Mamba (decoder)")
    
    print("\n  Difference: Only Mamba innovations")
    print("  Purpose: Measure the impact of hierarchical Mamba architecture")
    print("="*80)


# Example 3: Custom Mamba configuration
def example_custom_mamba_config():
    """
    Example of customizing Mamba configuration
    """
    from LogWeightednnUNetTrainer import TTrainer
    import torch
    
    # Initialize with default settings
    # trainer = TTrainer(plans, configuration, fold, dataset_json, device)
    
    # Customize Mamba configuration after initialization (before training)
    custom_config = {
        'd_state': 32,              # Increase state dimension (default: 16)
        'd_conv': 8,                # Increase conv size (default: 4)
        'expand': 4,                # Increase expansion factor (default: 2)
        'window_size': (8, 8, 8),   # Larger windows (default: (4,4,4))
        'overlap_ratio': 0.25,      # Less overlap (default: 0.5)
        'downsample_factor': 4      # More downsampling (default: 2)
    }
    
    print("Custom Mamba Configuration:")
    for key, value in custom_config.items():
        print(f"  {key}: {value}")
    
    # Note: To use custom config, modify trainer.mamba_config before 
    # calling initialize_network() or before first training step


# Example 4: Understanding the Mamba modules
def example_understanding_modules():
    """
    Explain what each Mamba module does
    """
    print("="*80)
    print("Hierarchical Mamba Architecture Explained")
    print("="*80)
    
    print("\n1. LocalMamba3D (Shallow Encoder - Stages 1-2)")
    print("   Purpose: Build strong local correlations")
    print("   Method: Partition into overlapping windows, apply Mamba per window")
    print("   Benefit: Linear complexity, strong local feature learning")
    print("   Example: Group all voxels of tooth enamel together")
    
    print("\n2. HierarchicalMamba3D (Middle Encoder - Stage 3)")
    print("   Purpose: Capture both organ-level and structure-internal relations")
    print("   Method: Parallel global (downsampled) + local (windowed) paths")
    print("   Benefit: Multi-scale feature extraction")
    print("   Example: Relate upper and lower jaw while preserving tooth details")
    
    print("\n3. ConditionalSelectiveMamba3D (Bottleneck)")
    print("   Purpose: Adapt Mamba parameters based on class statistics")
    print("   Method: Generate selective scan parameters from class priors")
    print("   Benefit: Handle extreme class imbalance dynamically")
    print("   Example: Adjust sensitivity based on class size distribution")
    
    print("\n4. SemanticGuidedMambaRefinement (Decoder)")
    print("   Purpose: Guide upsampling with global class information")
    print("   Method: Use global class vector to gate feature refinement")
    print("   Benefit: Class-aware feature recovery")
    print("   Example: Use class probabilities to guide detail restoration")
    
    print("="*80)


# Example 5: Monitoring training
def example_monitoring():
    """
    Example of what to monitor during training
    """
    print("="*80)
    print("Training Monitoring Guide")
    print("="*80)
    
    print("\nKey Metrics to Monitor:")
    print("  1. Total Loss (Dice + CE)")
    print("     - Should decrease steadily")
    print("     - Compare with TryTrainer baseline")
    
    print("\n  2. Per-class Dice scores")
    print("     - Focus on minority classes")
    print("     - Check if Mamba helps rare classes")
    
    print("\n  3. Memory usage")
    print("     - Window partition adds overhead")
    print("     - Adjust window_size if OOM occurs")
    
    print("\n  4. Training time per epoch")
    print("     - Mamba may be slower than CNN")
    print("     - Fallback to CNN if Mamba unavailable")
    
    print("\nExpected Improvements:")
    print("  ✅ Better Dice scores on minority classes")
    print("  ✅ More stable training (less variance)")
    print("  ✅ Better capture of long-range dependencies")
    print("  ✅ Improved handling of extreme class imbalance")
    
    print("="*80)


# Example 6: Troubleshooting
def example_troubleshooting():
    """
    Common issues and solutions
    """
    print("="*80)
    print("Common Issues and Solutions")
    print("="*80)
    
    issues = [
        {
            "issue": "CUDA Out of Memory",
            "solutions": [
                "Reduce window_size to (2,2,2) or (3,3,3)",
                "Reduce overlap_ratio to 0.25",
                "Reduce batch size",
                "Use gradient accumulation",
                "Disable some Mamba modules for testing"
            ]
        },
        {
            "issue": "Mamba not available warning",
            "solutions": [
                "Install: pip install mamba-ssm",
                "Or use fallback (automatic CNN replacement)",
                "Check CUDA version compatibility"
            ]
        },
        {
            "issue": "Attention gates import error",
            "solutions": [
                "Ensure 'attention_gates (1).py' is in same directory",
                "Check file permissions",
                "Verify Python path includes current directory"
            ]
        },
        {
            "issue": "Training slower than expected",
            "solutions": [
                "Normal - Mamba is more complex than CNN",
                "Consider reducing d_state or expand",
                "Use mixed precision training (AMP)",
                "Profile to find bottlenecks"
            ]
        },
        {
            "issue": "No improvement over TryTrainer",
            "solutions": [
                "Train longer (Mamba may need more epochs)",
                "Adjust Mamba hyperparameters",
                "Check if class imbalance is extreme enough",
                "Verify Mamba modules are actually being used"
            ]
        }
    ]
    
    for i, item in enumerate(issues, 1):
        print(f"\n{i}. {item['issue']}")
        print("   Solutions:")
        for solution in item['solutions']:
            print(f"     - {solution}")
    
    print("\n" + "="*80)


if __name__ == "__main__":
    print("\n" + "="*80)
    print("TTrainer Usage Examples")
    print("="*80 + "\n")
    
    # Run examples
    example_understanding_modules()
    print("\n")
    
    example_ablation_study()
    print("\n")
    
    example_monitoring()
    print("\n")
    
    example_troubleshooting()
    print("\n")
    
    # Note about actual usage
    print("="*80)
    print("Note: To actually train with TTrainer:")
    print("="*80)
    print("1. Prepare your dataset in nnUNet format")
    print("2. Run nnUNet preprocessing:")
    print("   nnUNetv2_plan_and_preprocess -d DATASET_ID")
    print("3. Train with TTrainer:")
    print("   nnUNetv2_train DATASET_ID 3d_fullres FOLD -tr TTrainer")
    print("4. Compare with TryTrainer baseline:")
    print("   nnUNetv2_train DATASET_ID 3d_fullres FOLD -tr TryTrainer")
    print("="*80 + "\n")
